//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StankiEntities : DbContext
    {
        public StankiEntities()
            : base("name=StankiEntities")
        {
        }

        private static StankiEntities _context;
        public static StankiEntities GetContext()
        {
            if (_context == null)
                _context = new StankiEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<RepairRequest> RepairRequest { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestRequests> TestRequests { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
